# https://github.com/mongodb/mongoid/blob/master/lib/rails/generators/mongoid/config/templates/mongoid.yml
development:
  clients:
    default:
      uri: <%= "#{ENV['MONGODB_URI']}_development" %>

test:
  clients:
    default:
      uri: <%= "#{ENV['MONGODB_URI']}_test" %>
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        connect_timeout: 15
